name: Deploy Project Template

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_NICK: ${{ secrets.BOT_NICK }}
      MY_CHANNEL: ${{ secrets.MY_CHANNEL }}
      AWS_SERVER_KEY: ${{ secrets.AWS_SERVER_KEY }}
    
    steps:
      - name: Set up SSH key
        uses: jwalton/gh-ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SERVER_KEY }}

      - name: SSH into AWS VM
        uses: appleboy/ssh-action@master
        with:
          host: 16.171.40.78
          username: "ubuntu"
          key: ${{ secrets.AWS_SERVER_KEY }}
          port: 22
          script: |
            cd Media-Loader-Bot/
            git pull
            sleep 5
            echo BOT_TOKEN=$BOT_TOKEN > .env
            echo BOT_NICK=$BOT_NICK >> .env
            echo MY_CHANNEL=$MY_CHANNEL >> .env
            npm i
            sleep 10
            pm2 delete bot
            sleep 4
            pm2 start Media-Loader-Bot/index.js --name bot
      
   
