name: Deploy Project Template

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: |
          echo ${{ secrets.AWS_SERVER_KEY }} > key.pem
          ssh -i key.pem ubuntu@16.171.40.78
          sleep 4
          cd Media-Loader-Bot/
          npm i
          sleep 10
          pm2 delete bot
          sleep 4
          pm2 start Media-Loader-Bot/index.js --name bot
      
   
